config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    resource :avior_tax_settings
    post '/avior_tax_settings/login', to: 'avior_tax_settings#login', as: :avior_tax_login
  end
end

app/models/spree_avior_tax/address_decorator.rb
module SpreeAviorTax
  module AddressDecorator
    def self.prepended(base)
      base::ADDRESS_FIELDS << 'county' unless base::ADDRESS_FIELDS.include?('county')
      base.validates :county, presence: true
    end
  end
end

Spree::Address.prepend SpreeAviorTax::AddressDecorator

app/models/spree_avior_tax/avior_tax.rb
module SpreeAviorTax
  class AviorTax
    attr_reader :order, :line_item, :shipment, :client

    def initialize(order = nil, line_item = nil, shipment = nil)
      @order = order
      @line_item = line_item
      @shipment = shipment
      @client = SpreeAviorTax::Client.new client_params
    end

    delegate :login, to: :client

    def calculate_for_order(order, line_item)
      @order = order
      @line_item = line_item
      client.calculate_tax [line_item_params]
    end

    def calculate_for_shipment(order, shipment)
      @order = order
      @shipment = shipment
      client.calculate_tax [shipment_params]
    end

    private

    def client_params
      {
        service_url: SpreeAviorTax::Config[:service_url],
        token: SpreeAviorTax::Config[:token]
      }
    end

    def record_number(order)
      order.number.gsub(/^R/, '')
    end

    def line_item_params
      SpreeAviorTax::API::Input::Product.new(
        date: order.updated_at.strftime('%Y%m%d'),
        record_number: record_number(order),
        seller_id: SpreeAviorTax::Config[:seller_id],
        seller_location_id: SpreeAviorTax::Config[:seller_location_id],
        seller_state: SpreeAviorTax::Config[:seller_state],
        customer_entity_code: SpreeAviorTax::Config[:customer_entity_code],
        delivery_method: 'N',
        ship_to_address: order.tax_address.address1,
        ship_to_suite: order.tax_address.address2,
        ship_to_city: order.tax_address.city,
        ship_to_county: order.tax_address.county,
        ship_to_state: order.tax_address.state.abbr,
        ship_to_zip_code: order.tax_address.zipcode,
        ship_to_zip_plus: '',
        sku: line_item.variant.sku,
        amount_of_sale: line_item.discounted_amount
      )
    end

    def shipment_params
      SpreeAviorTax::API::Input::Product.new(
        date: order.updated_at.strftime('%Y%m%d'),
        record_number: record_number(order),
        seller_id: SpreeAviorTax::Config[:seller_id],
        seller_location_id: SpreeAviorTax::Config[:seller_location_id],
        seller_state: SpreeAviorTax::Config[:seller_state],
        customer_entity_code: SpreeAviorTax::Config[:customer_entity_code],
        delivery_method: 'N',
        ship_to_address: order.tax_address.address1,
        ship_to_suite: order.tax_address.address2,
        ship_to_city: order.tax_address.city,
        ship_to_county: order.tax_address.county,
        ship_to_state: order.tax_address.state.abbr,
        ship_to_zip_code: order.tax_address.zipcode,
        ship_to_zip_plus: '',
        sku: '',
        amount_of_sale: shipment.discounted_cost
      )
    end
  end
end

app/models/spree_avior_tax/calculator/avior_tax_calculator.rb
module SpreeAviorTax
  module Calculator
    class AviorTaxCalculator < Spree::Calculator
      include Spree::VatPriceCalculation

      CACHE_EXPIRATION_DURATION = 10.minutes

      def self.description
        Spree.t(:avior_tax)
      end

      def compute_order(_order)
        raise NotImplementedError
      end

      def compute_line_item(item)
        return 0 unless SpreeAviorTax::Config[:enabled]
        return 0 if rate.included_in_price

        round_to_two_places(tax_for_line_item(item))
      end

      def compute_shipment(shipment)
        return 0 unless SpreeAviorTax::Config[:enabled]
        return 0 if rate.included_in_price

        round_to_two_places(tax_for_shipment(shipment))
      end

      def compute_shipping_rate(_shipping_rate)
        0
      end

      private

      def rate
        calculable
      end

      def tax_for_line_item(item)
        order = item.order
        tax_address = order.tax_address

        rails_cache_key = cache_key(order, item, tax_address)

        Rails.cache.fetch(rails_cache_key, expires_in: CACHE_EXPIRATION_DURATION) do
          response = AviorTax.new.calculate_for_order(order, item)
          sum_taxes_for_products(response)
        end
      end

      def tax_for_shipment(shipment)
        order = shipment.order
        tax_address = order.tax_address

        rails_cache_key = cache_key(order, shipment, tax_address)

        Rails.cache.fetch(rails_cache_key, expires_in: CACHE_EXPIRATION_DURATION) do
          response = AviorTax.new.calculate_for_shipment(order, shipment)
          sum_taxes_for_products(response)
        end
      end

      def sum_taxes_for_products(products)
        products.reduce(0) do |sum, product|
          sum + product.taxes.reduce(0) { |local_sum, tax| local_sum + BigDecimal(tax.fips_tax_amount) }
        end
      end

      def cache_key(order, item, address)
        if item.is_a?(Spree::LineItem)
          [Spree::LineItem.to_s, order.id, item.id, address.state_id, address.zipcode, item.taxable_amount, :amount_to_collect]
        else
          [Spree::Shipment.to_s, order.id, item.id, address.state_id, address.zipcode, item.cost, item.adjustments.reject do |adjustment|
                                                                                                    adjustment.source_type == Spree::TaxRate.to_s
                                                                                                  end.map(&:amount).sum.to_f, :amount_to_collect]
        end
      end
    end
  end
end

app/models/spree_avior_tax/configuration.rb
module SpreeAviorTax
  class Configuration < Spree::Preferences::Configuration
    preference :enabled, :boolean, default: true
    preference :user_id, :string
    preference :password, :string
    preference :service_url, :string
  end
end

app/models/spree_avior_tax/tax_rate_decorator.rb
module SpreeAviorTax
  module TaxRateDecorator
    private

    def label
      return super unless using_avior_tax?

      Spree.t :avior_tax_adjustment_label
    end

    def using_avior_tax?
      calculator_type == SpreeAviorTax::Calculator::AviorTaxCalculator.to_s
    end
  end
end

Spree::TaxRate.prepend SpreeAviorTax::TaxRateDecorator

app/controllers/spree/admin/avior_tax_settings_controller.rb
module Spree
  module Admin
    class AviorTaxSettingsController < Spree::Admin::BaseController
      def edit
        @basic_preferences_api = %i[service_url username password]
        @preferences_api = %i[enabled company_name token seller_id seller_location_id seller_state customer_entity_code]
        @us = Spree::Country.find_by(iso: 'US')
      end

      def update
        params.each do |name, value|
          SpreeAviorTax::Config[name] = value if SpreeAviorTax::Config.has_preference? name
        end

        flash[:success] = Spree.t(:avior_tax_settings_updated)
        redirect_to edit_admin_avior_tax_settings_path
      end

      def login
        validated_params = params.permit(:service_url, :username, :password)

        raise ActionController::ParameterMissing, :service_url unless validated_params.key?(:service_url)
        raise ActionController::ParameterMissing, :username unless validated_params.key?(:username)
        raise ActionController::ParameterMissing, :password unless validated_params.key?(:password)

        SpreeAviorTax::Config[:service_url] = validated_params[:service_url]

        client = SpreeAviorTax::Client.new(
          service_url: SpreeAviorTax::Config[:service_url]
        )

        data = client.login(validated_params[:username], validated_params[:password])

        if data['auth_token'].nil?
          flash[:error] = Spree.t(:avior_tax_login_failed)
          redirect_to edit_admin_avior_tax_settings_path
          return
        end
        SpreeAviorTax::Config[:username] = validated_params[:username]
        SpreeAviorTax::Config[:password] = validated_params[:password]
        SpreeAviorTax::Config[:token] = data['auth_token']

        redirect_to edit_admin_avior_tax_settings_path
      rescue SpreeAviorTax::API::Errors::AviorTaxServerError => e
        flash[:error] = e.response['non_field_errors'].join(', ')
        redirect_to edit_admin_avior_tax_settings_path
      end
    end
  end
end

app/views/spree/admin/avior_tax_settings/edit.html.erb
<%= render 'spree/admin/shared/sub_menu/configuration' %>
<% content_for :page_title do %>
  <%= Spree.t(:avior_tax_settings) %>
<% end %>
<%= form_tag admin_avior_tax_login_path, method: :post do %>
  <div data-hook="admin_tax_rate_form_fields">
    <div class="card mb-3" data-hook="tax_rates">
      <div class="card-header">
        <h5 class="card-title mb-0 h6">
          <%= Spree.t(:avior_tax_basic_settings) %>
        </h5>
      </div>

      <div class="card-body">
        <div id="basic-preferences" data-hook>
          <div class="row">
            <div class="col-md-6">
              <fieldset class="no-border-bottom">
                <% @basic_preferences_api.each do |key| %>
                  <div class="form-group">
                      <%= label_tag key %>
                      <%= preference_field_tag(key, SpreeAviorTax::Config[key], type: SpreeAviorTax::Config.preference_type(key)) %>
                  </div>
                <% end %>
              </fieldset>
            </div>
          </div>
          <div class="form-actions" data-hook="buttons">
            <%= button Spree.t('login'), 'submit', {class: 'btn-primary btn-block', data: { disable_with: "#{ Spree.t(:saving) }..." }} %>
          </div>
        </div>
      </div>

    </div>
  </div>
<% end %>

<% if SpreeAviorTax::Config[:token] %>
  <%= form_tag admin_avior_tax_settings_path, method: :put do %>
    <div data-hook="admin_tax_rate_form_fields">
      <div class="card mb-3" data-hook="tax_rates">
        <div class="card-header">
          <h5 class="card-title mb-0 h6">
            <%= Spree.t(:avior_tax_general_settings) %>
          </h5>
        </div>

        <div class="card-body">
          <div id="general-preferences" data-hook>
            <div class="row">
              <div class="col-md-6">
                <fieldset class="no-border-bottom">
                  <% @preferences_api.each do |key| %>
                    <div class="form-group">
                      <% if SpreeAviorTax::Config.preference_type(key) == :boolean %>
                        <div class="checkbox">
                          <%= label_tag key do %>
                            <%= hidden_field_tag(key, 0, id: "#{key}_hidden") %>
                            <%= check_box_tag(key, 1, SpreeAviorTax::Config[key]) %>
                            <%= Spree.t(key) %>
                          <%end%>
                        </div>
                      <% elsif key == :seller_state %>
                        <%= content_tag :div, class: 'form-group' do %>
                          <%= label_tag key %>
                          <%= select_tag key, options_from_collection_for_select(@us.states.sort, :abbr, :name, SpreeAviorTax::Config[key]), class: 'form-control state_name select2 w-100' %>
                        <% end %>
                      <% elsif key == :token %>
                          <%= label_tag key %>
                          <%= text_field_tag key, SpreeAviorTax::Config[key], class: 'form-control', disabled: true %>
                      <% else %>
                        <%= label_tag key %>
                        <%= preference_field_tag(key, SpreeAviorTax::Config[key], type: SpreeAviorTax::Config.preference_type(key)) %>
                      <% end %>
                    </div>
                  <% end %>
                </fieldset>
              </div>
            </div>
            <%= render partial: 'spree/admin/shared/edit_resource_links', locals: {collection_url: admin_orders_url}  %>
          </div>
        </div>

      </div>
    </div>
  <% end %>
<% end %>